batch_size: 32
epochs: 100
# opt: 'adamw'
# opt_eps: 1e-8
# opt_betas:
#   - 0.9
#   - 0.999
opt: 'sgd'
momentum: 0.9
weight_decay: 0.01
lr_base: 1. # base lr,  which will be auto-scaled: lr * batch size * nb_gpus / lr_base_size
lr_base_size: 256
lr_base_scale: linear
min_lr: 0.0 #  which will be auto-scaled: min_lr * batch size * nb_gpus / lr_base_size
sched: 'cosine'
warmup_epochs: 10
warmup_lr: 0.  # which will be auto-scaled: warmup_lr * batch size * nb_gpus / lr_base_size
cooldown_epochs: 0
# amp: True
# clip_grad: 5.0
no_aug: true
smoothing: 0.0
no_prefetcher: True
drop_path: 0.1
bias_tuning: false
